### ISSUE TITLE
error: Integrity check failed for remote specifier

### ISSUE THREAD

**Issue by masnagam** [ansanloms/mirakc-ui#2]
`README.md`に従ってイメージのビルドを実行したところ，以下のようなエラーが発生したため報告します．

```
6.974 error: Integrity check failed for remote specifier. The source code is invalid, as it does not match the expected hash in the lock file.
6.974
6.974   Specifier: https://esm.sh/*preact-render-to-string@6.3.1
6.974   Actual: 37f046906d7cc1ce35828a029a05a4eed6c8eefc4b646a301939757dfbf8ab18
6.974   Expected: 07807f027acf54b994b630bbb2a923f5a835f9544e01144f67ab292e90a431e4
6.974
6.974 This could be caused by:
6.974   * the lock file may be corrupt
6.974   * the source itself may be corrupt
6.974
[+] Building 0/1e the lockfile; delete it to regenerate the lockfile or --reload to reload the source code from the server.
```

実際に使用した`Dockerfile`:

```dockerfile
# `FROM docker.io/denoland/deno`に書き換えても同じエラーが発生する
FROM docker.io/denoland/deno:2.0.0

WORKDIR /app
EXPOSE 8000

RUN apt-get update && apt-get install -y curl tar
# v0.5.7 -> v0.5.8 に変更
# v0.5.7のままでも同じエラーが発生する
RUN curl -L https://github.com/ansanloms/mirakc-ui/archive/refs/tags/v0.5.8.tar.gz | tar -xz --strip-components 1
RUN rm .env.example
RUN deno cache ./main.ts --allow-import
RUN deno task build

CMD ["run", "-A", "./main.ts"]
```

`compose.yaml`からの抜粋:

```yaml
  mirakc-ui:
    container_name: mirakc-ui
    depends_on:
      - mirakc
    image: mirakc-ui
    build: ./mirakc-ui
    init: true
    restart: unless-stopped
    ports:
      - 8888:8000
    environment:
      MIRAKC_API_URL: http://mirakc:40772/api
```

実行したコマンド:

```shell
docker compose build mirakc-ui
```

なお，`FROM docker.io/denoland/deno:2.0.0`を`FROM docker.io/denoland/deno`に書き換えても同じ結果となります．

### workaround

```Dockerfile
...
# deno cacheの前にdeno.lockを削除
RUN rm deno.lock
RUN deno cache ./main.ts --allow-import
...
```

調査はしていませんが，何らかの理由で`deno.lock`が正しく更新されていなかったのか，`deno`の不具合かなにかで`deno.lock`が正しく機能していないのかもしれません．
